{
 "title": "Demo Microservice Dashboard",
 "tags": [
  "demo",
  "microservice"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{container_name=\"grafana\"})",
     "legendFormat": "Grafana"
    },
    {
     "expr": "avg(container_memory_usage_bytes{container_name=\"prometheus-server\"})",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "avg(container_memory_usage_bytes{container_name=\"neo4j-neo4j\"})",
     "legendFormat": "Neo4j"
    },
    {
     "expr": "avg(container_memory_usage_bytes{container_name=\"rabbitmq\"})",
     "legendFormat": "RabbitMQ"
    },
    {
     "expr": "avg(container_memory_usage_bytes{container_name=\"demo\"})",
     "legendFormat": "Demo"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_system_seconds_total{container_name=\"grafana\"}[2m]))",
     "legendFormat": "Grafana"
    },
    {
     "expr": "avg(rate(container_cpu_system_seconds_total{container_name=\"prometheus-server\"}[2m]))",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "avg(rate(container_cpu_system_seconds_total{container_name=\"neo4j-neo4j\"}[2m]))",
     "legendFormat": "Neo4j"
    },
    {
     "expr": "avg(rate(container_cpu_system_seconds_total{container_name=\"rabbitmq\"}[2m]))",
     "legendFormat": "RabbitMQ"
    },
    {
     "expr": "avg(rate(container_cpu_system_seconds_total{container_name=\"demo\"}[2m]))",
     "legendFormat": "Demo"
    }
   ]
  },
  {
   "title": "Request time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_response_duration_seconds_sum{ingress=\"demo\"}) / sum(nginx_ingress_controller_response_duration_seconds_count{ingress=\"demo\"})",
     "legendFormat": "Nginx"
    },
    {
     "expr": "sum(persons_findall_seconds_sum) / sum(persons_findall_seconds_count)"
    }
   ]
  }
 ]
}