{
 "title": "Demo Microservice Dashboard",
 "tags": [
  "demo",
  "microservice"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{container_name=\"grafana\"})",
     "legendFormat": "Grafana"
    },
    {
     "expr": "avg(container_memory_usage_bytes{container_name=\"prometheus-server\"})",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "avg(container_memory_usage_bytes{container_name=\"neo4j-neo4j\"})",
     "legendFormat": "Neo4j"
    },
    {
     "expr": "avg(container_memory_usage_bytes{container_name=\"rabbitmq\"})",
     "legendFormat": "RabbitMQ"
    },
    {
     "expr": "avg(container_memory_usage_bytes{container_name=\"conference-backend\"})",
     "legendFormat": "Conference Backend"
    },
    {
     "expr": "avg(container_memory_usage_bytes{container_name=\"conference-frontend\"})",
     "legendFormat": "Conference Frontend"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_system_seconds_total{container_name=\"grafana\"}[2m]))",
     "legendFormat": "Grafana"
    },
    {
     "expr": "avg(rate(container_cpu_system_seconds_total{container_name=\"prometheus-server\"}[2m]))",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "avg(rate(container_cpu_system_seconds_total{container_name=\"neo4j-neo4j\"}[2m]))",
     "legendFormat": "Neo4j"
    },
    {
     "expr": "avg(rate(container_cpu_system_seconds_total{container_name=\"rabbitmq\"}[2m]))",
     "legendFormat": "RabbitMQ"
    },
    {
     "expr": "avg(rate(container_cpu_system_seconds_total{container_name=\"conference-backend\"}[2m]))",
     "legendFormat": "Conference Backend"
    },
    {
     "expr": "avg(rate(container_cpu_system_seconds_total{container_name=\"conference-frontend\"}[2m]))",
     "legendFormat": "Conferene Frontend"
    }
   ]
  },
  {
   "title": "Request time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_response_duration_seconds_sum{ingress=\"conference-backend\"}) / sum(nginx_ingress_controller_response_duration_seconds_count{ingress=\"conference-backend\"})",
     "legendFormat": "Conference Backend"
    },
    {
     "expr": "sum(nginx_ingress_controller_response_duration_seconds_sum{ingress=\"conference-frontend\"}) / sum(nginx_ingress_controller_response_duration_seconds_count{ingress=\"conference-frontend\"})",
     "legendFormat": "Conference Frontend"
    },
    {
     "expr": "sum(persons_findall_seconds_sum) / sum(persons_findall_seconds_count)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "nginx_ingress_controller_nginx_process_requests_total"
    }
   ]
  }
 ]
}