apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.name" . }}
  labels:
    app: {{ include "application.name" . }}
data:
  application.yaml: |-
    server:
      port: 80
    spring:
      data:
        neo4j:
          uri: {{ .Values.neo4j.uri }}
    conference:
      backend:
        url: http://conference-backend
