server:
  port: 8080
spring:
  application:
    name: demo
  servlet:
    multipart:
      enabled: true
      location: /tmp
  cloud:
    kubernetes:
      discovery:
        enabled: true
      reload:
        enabled: false
      config:
        enabled: true
  data:
    neo4j:
      uri: bolt://192.168.99.100:32001
    rest:
      basePath: /api
management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints:
    web:
      exposure.include: info,health,metrics,prometheus
  metrics:
    export.prometheus.enabled: true
    web:
      server:
        auto-time-requests: true
  security:
    enabled: false
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    exception-handlers-enabled: true
graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  static:
    basePath: /
  pageTitle: Conference GraphQL Server
  cnd:
    enabled: false
