server:
  port: 8080
spring:
  application:
    name: demo
  cloud:
    kubernetes:
      discovery:
        enabled: true
      reload:
        enabled: false
      config:
        enabled: true
  data:
    neo4j:
      uri: bolt://neo4j
management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints:
    web:
      exposure.include: info,health,metrics,prometheus
  metrics:
    export.prometheus.enabled: true
    web:
      server:
        auto-time-requests: true
  security:
    enabled: false
