apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.name" . }}
  labels:
    app: {{ include "application.name" . }}
data:
  application.yaml: |-
    server:
      port: 80
    conference:
      backend:
        url: {{ .Values.conference.backend.uri }}
