apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: conference-frontend
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: conference-frontend
  targetCPUUtilizationPercentage: 30

