ingress:
  enabled: true
  tls:
  - hosts:
    - conference.minikube
    secretName: minikube
  hosts: 
  - conference.minikube
image:
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 1500m
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 1Gi
