ingress:
  enabled: true
  tls:
  - hosts:
    - conference.minikube
    secretName: minikube
  hosts: 
  - conference.minikube
image:
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 2000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 1Gi
