#!/bin/bash
KEY_FILE=key.pem
CERT_FILE=cert.pem
HOST="*.minikube"
SECRET="minikube"
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ${KEY_FILE} -out ${CERT_FILE} -subj "/CN=${HOST}/O=${HOST}"
for NAMESPACE in conference monitoring
do
	kubectl -n ${NAMESPACE} delete secret ${SECRET}
	kubectl -n ${NAMESPACE} create secret tls ${SECRET} --key ${KEY_FILE} --cert ${CERT_FILE}
done
rm ${KEY_FILE} ${CERT_FILE}

