apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo.name" . }}
  labels:
    app: {{ include "demo.name" . }}
data:
  application.yaml: |-
    server:
      port: 80
    spring:
      data:
        neo4j:
          uri: {{ .Values.neo4j.uri }}
