apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: microservice
  labels:
    component: microservice
rules:
- apiGroups: [""] 
  resources: ["configmaps","secrets"]
  resourceNames: ["microservice"]
  verbs: ["get","watch","list"]
- apiGroups: [""] 
  resources: ["pods","services"]
  verbs: ["get","watch","list"]

