ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.global-static-ip-name: conference-ip
image:
  pullPolicy: Always
service:
  type: NodePort
neo4j:
  uri: bolt://neo4j-neo4j.persistence
resources:
  limits:
    cpu: 1500m
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 1Gi
