ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.global-static-ip-name: conference-ip
image:
  pullPolicy: Always
service:
  type: NodePort
neo4j:
  uri: bolt://neo4j-neo4j.persistence
