ingress:
  enabled: true
  tls:
  - hosts:
    - conference.minikube
    secretName: minikube
  hosts: 
  - conference.minikube
image:
  pullPolicy: IfNotPresent
neo4j:
  uri: bolt://neo4j-neo4j.persistence
resources:
  cpu: 1
  memory: 1Gi
resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

