ingress:
  enabled: true
  tls:
  - hosts:
    - conference.minikube
    secretName: minikube
  hosts: 
  - conference.minikube
image:
  pullPolicy: IfNotPresent
neo4j:
  uri: bolt://neo4j-neo4j.persistence
resources:
  cpu: 1
  memory: 1Gi
resources:
  limits:
    cpu: 150m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 1Gi

