authEnabled: false
imageTag: 3.5.0-enterprise
acceptLicenseAgreement: "yes"
core:
  numberOfServers: 1
  extraVars:
  - name: NEO4J_dbms_mode
    value: "SINGLE"
  - name: NEO4J_metrics_enabled
    value: "true"
  - name: NEO4J_metrics_prometheus_enabled
    value: "true"
  - name: NEO4J_metrics_prometheus_endpoint
    value: "0.0.0.0:2004"
  - name: NEO4J_dbms__security__allow_csv_import_from_file_urls
    value: "true"
