apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2018-12-13T12:09:45Z"
  labels:
    app: neo4j
    chart: neo4j-0.8.0
    component: core
    heritage: Tiller
    release: neo4j
  name: neo4j-nodeport
  namespace: persistence
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "2004"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  ports:
    - port: 7474
      protocol: TCP
      targetPort: 7474
      nodePort: 32010
      name: http
    - port: 7687
      protocol: TCP
      targetPort: 7687
      nodePort: 32011
      name: bolt
  selector:
    app: neo4j
    component: core
    release: neo4j
  sessionAffinity: None
