persistence:
  enabled: true
  size: 1G
  accessModes:
  - ReadWriteOnce
ingress: 
  enabled: true
  tls:
  - hosts:
    - "grafana.minikube"
    secretName: minikube
  hosts: 
  - "grafana.minikube"
sidecar:
  dashboards:
    enabled: true
    searchNamespace: monitoring
    label: grafana-dashboard
  datasources:
    enabled: true
    searchNamespace: monitoring
    label: grafana-datasource
